from enum import IntEnum

class PhCommand(IntEnum):
    MSG_ACK  =  0
    MSG_NACK  =  1
    MSG_RESERVED_1 = 2
    MSG_RESERVED_2 = 3
    MSG_PRESS_KEY = 4    # Used by WebServer to send key presses
    MSG_SET_VALUE = 5
    MSG_SET_TEXT = 6
    MSG_SET_ENABLE = 7
    MSG_SET_VISIBLE = 8
    MSG_SET_COLOUR = 9
    MSG_CLEAR_ITEMS = 10
    MSG_ADD_ITEM_VALUE = 11
    MSG_SET_ITEM_TEXT = 12
    MSG_SET_ITEM_VALUE = 13
    MSG_SET_ITEM_TEXT_VALUE = 14
    MSG_SET_ITEM_ENABLED = 15
    MSG_SET_ITEM_VALUES = 16
    MSG_SET_ITEM_STRINGS = 17
    MSG_SET_FOCUS = 18
    MSG_GET_TEXT = 20
    MSG_GET_VALUE = 21
    MSG_GET_COLOUR = 22
    MSG_GET_ITEM_COUNT = 23
    MSG_GET_ITEM_VALUE = 24
    MSG_GET_ITEM_TEXT = 25
    MSG_GET_ITEM_TEXT_VALUE = 26
    MSG_GET_ITEM_ENABLED = 27
    MSG_GET_ITEM_VALUES = 28
    MSG_GET_ITEM_STRINGS = 29
    MSG_RET_TEXT = 30
    MSG_RET_VALUE = 31
    MSG_RET_COLOUR = 32
    MSG_RET_ITEM_COUNT = 33
    MSG_RET_ITEM_VALUE = 34
    MSG_RET_ITEM_TEXT = 35
    MSG_RET_ITEM_TEXT_VALUE = 36
    MSG_RET_ITEM_ENABLED = 37
    MSG_RET_ITEM_VALUES = 38
    MSG_RET_ITEM_STRINGS = 39
    MSG_SET_COLUMN_COUNT = 40
    MSG_GET_COLUMN_COUNT = 41
    MSG_RET_COLUMN_COUNT = 42
    MSG_SET_ROW_COUNT = 43
    MSG_GET_ROW_COUNT = 44
    MSG_RET_ROW_COUNT = 45
    MSG_SET_COLUMN_WIDTH = 46
    MSG_GET_COLUMN_WIDTH = 47
    MSG_RET_COLUMN_WIDTH = 48
    MSG_SET_ITEM_COLOUR = 49
    MSG_GET_ITEM_COLOUR = 50
    MSG_RET_ITEM_COLOUR = 51


class PhMsgError(IntEnum):
    MSG_ERR_OK  =  0
    MSG_ERR_CMDTYPE  =  -1  # invalid CommandType
    MSG_ERR_CMD_ID  =  -2   # invalid CommandID
    MSG_ERR_STR_LENGTH = -3 # StringLength too long
    MSG_ERR_INDEX = -4      # ItemIndex too large
    MSG_ERR_DISABLED = -5   # Remote Control is disabled


